version: 0.1
component: build
runAs: root
shell: bash
env:
  variables:
    "testEnv" : "testEnvValue"
  exportedVariables:
    - testEnv
    - minor_version
#  vaultVariables:
#    "bankPassword": "ocid1.vaultsecret.oc1.iad.amaaaaaa34lgq7aa325l6x7exbl5y7c4pk75aodriekuttjkuqatetll35aq"       # secret-id (in OCI ID format) STORED IN OCI Vault Service
# inputArtifacts:
#   - name: hello-dev-jar
#     location: hello123.class

steps:
  - type: Command
    name: "Build Source 1"
    command: |
      echo "hello world"
      minor_version=20
      echo $minor_version
  - type: Command
    name: "Build Source 2"
    command: |
      echo "hello world"
      minor_version=22
      echo $minor_version
